---
- hosts: 192.168.56.5
  tasks:
   - name: add-key
     apt_key:
       url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
   - name: create file
     file:
       path: /etc/apt/sources.list.d/jenkins.list
       state: touch
   - name: repositry
     lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: 'deb https://pkg.jenkins.io/debian-stable binary/'
   - name: update
     apt:
       update_cache: yes
   - name: jenkins install
     apt: name=jenkins state=present
